box: wercker/step-shellcheck
build:
    steps:
        shellcheck:
            files: file.sh|test.sh
            separator: "|"
deploy:
    steps:
        - script:
            name: none
            code: |
                :
